- name: Install all dependecies
  become: true
  apt:
    name: "{{ list_of_packages }}"
    state: present
    update_cache: yes

- name: Add Docker GPG apt key
  become: true
  shell:
    cmd: "install -m 0755 -d /etc/apt/keyrings"

- name: Add Docker GPG apt key 2
  become: true
  shell:
    cmd: "curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"

- name: Add Docker GPG apt key 2
  become: true
  shell:
    cmd: "chmod a+r /etc/apt/keyrings/docker.gpg"

- name: Add Docker repository
  become: true
  shell:
    cmd: 'echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null'

- name: Update apt and install docker
  become: true
  apt:
    update_cache: yes
    name: "{{ docker_packages }}"
    state: latest